#!/bin/sh

#         --resnet \

# /users/nfs/Enseignants/piwowarski/venv/3.7/amal/bin/python  lit_image_classifier.py \
#         --fit \
#         --learning_rate 0.0001\
#         --data_path '/tempory/cifar10'\
#         --batch_size 32 \
#         --image_size 224 \
#         --num_workers 16 \
#         --patch_size 16 \
#         --emb_dim 512 \
#         --mlp_dim 1024 \
#         --num_heads 32 \
#         --num_layers 16 \
#         --num_classes 10 \
#         --attn_dropout_rate 0.0 \
#         --dropout_rate 0.1 \
#         --progress_bar_refresh_rate 20 \
#         --gpus -1\
#         --default_root_dir $1\
#         --resume_from_checkpoint $2\

# --fit \
# --max_epoch 5\
# --gpus -1\

dir=$1
mkdir -p "${dir}/cifar10"
mkdir -p "${dir}/model"

python    lit_image_classifier.py \
	--fit\
	--gpus -1\
        --default_root_dir "${dir}/model" \
        --learning_rate 0.001\
        --data_path "${dir}/cifar10"\
        --batch_size 10\
	--t_max 50\
        --image_size 256\
        --num_workers 14\
        --patch_size 16\
        --emb_dim 768\
        --mlp_dim 2048\
        --num_heads 32\
        --num_layers 12\
        --num_classes 10 \
        --attn_dropout_rate 0.0 \
        --dropout_rate 0.3 \
        --progress_bar_refresh_rate 20 \
#        --resume_from_checkpoint $2\
